### ISSUE TITLE
Not working in futur version of Redmine 4.x

### ISSUE THREAD

**Issue by abrochet** [team888/redmine-issue_mail_with_attachments-plugin#7]
Hello,

The plugin is not compatible with the new version of Redmine 4.0 Rails 5.2 :(
The method "alias_method_chain" is missing in the new version of Rails 5.x
Obviously, it must be replaced by the method "prepend" but I do not know Ruby enough for that...

Is it possible to correct?

**Comment by hhokawa777** [comment]
Hi
Thanks for your report. I will try to fix this.
(I should have used prepend just by ignoring ruby 1.x)

**Comment by LapshinIV** [comment]
Hello guys! thanks for the great plugin! but it doesn't work with RM 4.0 :( i have the same problem

Any news about compatible with Redmine 4.0?????

**Comment by eugene495** [comment]
but it doesn't work with RM 4.1 :(

**Comment by nobless** [comment]
Hello, any news here with 4.1, 4.2 ?

**Comment by hhokawa777** [comment]
I just merged a contribution to redmine-4-sparunakian branch. Additional work remained for release but you can try..

**Comment by gessel** [comment]
Working with Redmine 4.1

I installed ver4support_merge branch on my redmine install and it seems to work correctly.  Pull the src folder out was a bit odd, but no problem once sorted out.  

Environment:
  Redmine version                4.1.1.stable
  Ruby version                   2.6.6-p146 (2020-03-31) [amd64-freebsd11]
  Rails version                  5.2.4.3
  Environment                    production
  Database adapter               Mysql2

**Comment by mreichh** [comment]
Thanks a lot! Also worked for me running Redmine 4.1.1.stable, after I manually changed issue_mail_with_attachments/Gemfile

`#gem 'public_suffix', '4.0.5'`
`gem 'public_suffix', '4.0.6'`

because 4.0.6 seems to be a requirement by Redmine 4.1.1.

**Issues created/commented within** Redmine now include attachments into mail notifications. 

Though, this does not work if I **create/comment an issue via mail** (see https://www.redmine.org/projects/redmine/wiki/RedmineReceivingEmails#Enabling-unknown-users-to-create-issues-by-email). In this case, again, attachments are just not added to notifications.

Is this intentional behaviour from this plugin?

Environment:
  Redmine version                4.1.1.stable
  Ruby version                   2.5.5-p157 (2019-03-15) [x86_64-linux-gnu]
  Rails version                  5.2.4.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp

**Comment by hhokawa777** [comment]
'public_suffix', '4.0.6' is committed. Incoming mail was out of scope and not tested yet. Thank you for your reporting !

**Comment by nobless** [comment]
is 4.2.1 supported ?

**Comment by cham65** [comment]
Hi all !

I tried to install it on 4.2.1
I got this error : 
bundler could not find compatible versions for gem capybara
Many thanks for your help 

Environment:
  Redmine version                4.2.3.stable
  Ruby version                   2.6.8-p205 (2021-07-07) [x64-mingw32]
  Rails version                  5.2.6
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.34.0

**Comment by hhokawa777** [comment]
@cham65 
Thanks for your reporting.
I haven't tested the compatibility with 4.2 enough, but I think your error should be fixed by following change, right ?

branch:
ver4support_merge

file location:
src/issue_mail_with_attachments/Gemfile

pls change the string:
	gem 'site_prism', '3.5'
to:
	gem 'site_prism', '3.7'

**Comment by wontroba666** [comment]
hello, has anyone managed to run on 4.2?

on my version 4.2.3 unfortunately it does not work, I used ver4support_merge, I changed the Gemfile, unfortunately it still does not work
